[build]
    functions = "api"
    publish = "client"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 301
  force = true
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"