[build]
    functions = "api"
    publish = "client"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  force = true
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"